version: "3.8"

networks:
  brimove-network:
    driver: bridge
    name: brimove-network

services:
  postgresdb:
    image: postgres:alpine
    container_name: postgres_brimove
    restart: always
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - brimove-network
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  brimobile:
    build: .
    ports:
      - target: 7130
        published: 7130
        protocol: tcp
        mode: host
    restart: always
    networks:
      - brimove-network
    depends_on:
      - postgresdb
