package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"brimobile/graph/model"
	"context"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, uname string, pass string) (*model.CreateAccountResponse, error) {
	return r.AccService.CreateAccount(ctx, uname, pass)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, uname string, pass string, idNum string, deviceID string) (*model.LoginResponse, error) {
	return r.AccService.Login(ctx, uname, pass, idNum, deviceID)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (string, error) {
	return r.AccService.Logout(ctx, refreshToken)
}

// InsertSaving is the resolver for the insertSaving field.
func (r *mutationResolver) InsertSaving(ctx context.Context, input model.InsertSavingRequest) (*model.InqAccountSaving, error) {
	return r.SavingService.Insert(ctx, input)
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, uname string) (*model.AccountResponse, error) {
	return r.AccService.Account(ctx, uname)
}

// InqAccountSaving is the resolver for the inqAccountSaving field.
func (r *queryResolver) InqAccountSaving(ctx context.Context, accountNumber string) (*model.InqAccountSaving, error) {
	return r.SavingService.InqAccountSaving(ctx, accountNumber)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
