// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountResponse struct {
	ID    int    `json:"id"`
	Uname string `json:"uname"`
	Pass  string `json:"pass"`
}

type CreateAccountResponse struct {
	ID    int    `json:"id"`
	Uname string `json:"uname"`
	Pass  string `json:"pass"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}
