DROP DATABASE IF EXISTS brimoveapp;

CREATE DATABASE brimoveapp;

\c brimoveapp;

CREATE TABLE "accounts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uname" varchar(256) NOT NULL,
    "pass" varchar(256) NOT NULL,
    "access_token" varchar(256) NULL,
    "refresh_token" varchar(256) NULL
);

CREATE TABLE "saving" (
      "account_number" varchar(256) PRIMARY KEY NOT NULL,
      "account_type" varchar(256) NOT NULL,
      "branch_code" varchar(256) NOT NULL,
      "short_name" varchar(300) NOT NULL,
      "currency" varchar(3) NOT NULL,
      "cbal" varchar(256) NOT NULL,
      "hold" varchar(256) NOT NULL,
      "opening_date" varchar(256) NOT NULL,
      "product_group" varchar(256) NOT NULL,
      "product_name" varchar(256) NOT NULL,
      "status" varchar(1) NOT NULL
);

CREATE TABLE "brinjournalseq" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "branch_code" varchar(256) NOT NULL,
      "joirnalseq" integer NOT NULL
);

CREATE INDEX ON "saving" ("account_number");

CREATE INDEX ON "brinjournalseq" ("branch_code");